'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Reports
    
    Partial Public Class Index
        
        '''<summary>
        '''litReportTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReportTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phItemReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phItemReport As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlClients control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlClients As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''rptItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptItems As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''hidSelectedItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSelectedItemID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''phItemInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phItemInfo As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litItemDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litItemDescription As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litItemVendorName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litItemVendorName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litItemPartNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litItemPartNum As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''rptItemReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptItemReport As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''trNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trNoData As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''litTotalUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalUnit As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litTotalCost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalCost As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''panItemReportExcelExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panItemReportExcelExport As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''btnItemReportExportCsv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnItemReportExportCsv As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''btnItemReportExportExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnItemReportExportExcel As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''phStoreManagerReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phStoreManagerReport As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''btnStoreManagerReportExportCsv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnStoreManagerReportExportCsv As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''btnStoreManagerReportExportExcel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnStoreManagerReportExportExcel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
