'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Docs
    
    Partial Public Class Index
        
        '''<summary>
        '''btnDeleteAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDeleteAll As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''Alert1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Alert1 As Global.IOF.Web.BootstrapAlert
        
        '''<summary>
        '''phNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phNoData As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rptFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptFiles As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
