'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls
    
    Partial Public Class PurchaseOrderHeaderView
        
        '''<summary>
        '''btnPurchaseOrderInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPurchaseOrderInfo As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lblPurchaseOrderInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPurchaseOrderInfo As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''litPOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPOID As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''lblStatusID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatusID As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblCopyIOF control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCopyIOF As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''phRealPO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phRealPO As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litRealPO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litRealPO As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litVendorName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litVendorName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litApprovedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litApprovedBy As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litNeededDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNeededDate As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litOversized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litOversized As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litShippingMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litShippingMethod As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litIsInventoryControlled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litIsInventoryControlled As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litOrderedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litOrderedBy As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNotes As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
