'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PurchaseOrderAttachments
    
    '''<summary>
    '''hidPOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidReadOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidReadOnly As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''phUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phUpload As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''fuAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuAttachments As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnAddAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAttachment As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAttachments As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''phNoAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phNoAttachments As Global.System.Web.UI.WebControls.PlaceHolder
End Class
