'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls
    
    Partial Public Class PurchaseOrderDetailView
        
        '''<summary>
        '''hidPOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidPOID As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''btnPurchaseOrderItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPurchaseOrderItems As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lblPurchaseOrderItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPurchaseOrderItems As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''rptItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptItems As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''phNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phNoData As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''phUpdateOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phUpdateOption As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
