'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls
    
    Partial Public Class PurchaseOrderSearch
        
        '''<summary>
        '''litTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phStoreManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phStoreManager As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''chkStoreManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStoreManager As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDate As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''ddlVendors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlVendors As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtVendorName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtVendorName As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtKeywords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtKeywords As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtPartNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPartNumber As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtPOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPOID As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtShortCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtShortCode As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''ddlClients control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlClients As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''odsClients control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsClients As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''chkIncludeSelf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeSelf As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    End Class
End Namespace
