'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls
    
    Partial Public Class PurchasingSearch
        
        '''<summary>
        '''hidStatusIDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidStatusIDs As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''litTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phPOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phPOID As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''txtPOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPOID As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''phPurchaser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phPurchaser As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlPurchaser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPurchaser As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''phCreator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCreator As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlCreator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCreator As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''phRealPO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phRealPO As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''txtRealPO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRealPO As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''phDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDateRange As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlDatePresets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDatePresets As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''phClaimStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phClaimStatus As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rdoClaimStatusUnclaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoClaimStatusUnclaimed As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoClaimStatusClaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoClaimStatusClaimed As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoClaimStatusClaimedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoClaimStatusClaimedBy As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoClaimStatusAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoClaimStatusAll As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''litDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDebug As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
