'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ApprovalList
    
    '''<summary>
    '''hidCurrentPOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCurrentPOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''phApprovalList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phApprovalList As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''phFilterAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phFilterAlert As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''litFilterAlertName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litFilterAlertName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''hypViewAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypViewAll As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''ApproveAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApproveAlert As Global.IOF.Web.BootstrapAlert
    
    '''<summary>
    '''phReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phReject As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''txtRejectReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRejectReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hidIsApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsApprover As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''phMine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phMine As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''litApproverName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litApproverName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''thApproveRejectHeaderMine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thApproveRejectHeaderMine As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''rptApprovalPendingMine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptApprovalPendingMine As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''litOtherApproverName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOtherApproverName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''thApproveRejectHeaderOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thApproveRejectHeaderOther As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''rptApprovalPendingOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptApprovalPendingOther As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''panDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panDetail As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PurchaseOrderHeaderView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderHeaderView1 As Global.IOF.Web.Controls.PurchaseOrderHeaderView
    
    '''<summary>
    '''PurchaseOrderDetailView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderDetailView1 As Global.IOF.Web.Controls.PurchaseOrderDetailView
    
    '''<summary>
    '''hypPrintIOF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypPrintIOF As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
