'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CopyData
    
    '''<summary>
    '''ddlCopyToClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCopyToClient As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''phCopyToClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCopyToClientName As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''litCopyToClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCopyToClientName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''hidCopyToClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCopyToClientID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ddlCopyFromClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCopyFromClient As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCopyFromVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCopyFromVendor As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkCopyFromIncludeItems0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCopyFromIncludeItems0 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''btnCopyData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyData As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Alert1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Alert1 As Global.IOF.Web.BootstrapAlert
End Class
