'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderedIOF
    
    '''<summary>
    '''hidPOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPOID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''phPrivMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPrivMessage As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''phSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phSearch As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''PurchasingSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchasingSearch1 As Global.IOF.Web.Controls.PurchasingSearch
    
    '''<summary>
    '''rptOrdered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptOrdered As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''phDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phDetail As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lblClaimedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtReqNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReqNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divRealPoFormGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRealPoFormGroup As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtRealPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRealPO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRealPOSaveError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRealPOSaveError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PurchaseOrderHeaderView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderHeaderView1 As Global.IOF.Web.Controls.PurchaseOrderHeaderView
    
    '''<summary>
    '''PurchaseOrderDetailView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderDetailView1 As Global.IOF.Web.Controls.PurchaseOrderDetailView
    
    '''<summary>
    '''txtPurchaserNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaserNotes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PurchaseOrderAttachments1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderAttachments1 As Global.IOF.Web.PurchaseOrderAttachments
    
    '''<summary>
    '''phCancelOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCancelOrder As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''btnCancelOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CancelOrderAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelOrderAlert As Global.IOF.Web.BootstrapAlert
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hypPrintIOF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypPrintIOF As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
