'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POConfirm

    '''<summary>
    '''phConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phConfirm As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''PurchaseOrderHeaderView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderHeaderView1 As Global.IOF.Web.Controls.PurchaseOrderHeaderView

    '''<summary>
    '''PurchaseOrderDetailView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderDetailView1 As Global.IOF.Web.Controls.PurchaseOrderDetailView

    '''<summary>
    '''PurchaseOrderAttachments1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderAttachments1 As Global.IOF.Web.PurchaseOrderAttachments

    '''<summary>
    '''hypPrintIOF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypPrintIOF As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''btnSendToApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendToApprover As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSendToPurchaser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendToPurchaser As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMarkCompleteAndPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMarkCompleteAndPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnKeepDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKeepDraft As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hypReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypReturn As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''phPOMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPOMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''litPOMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPOMessage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''panSetAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSetAccount As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hidSetAccountPOID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSetAccountPOID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''litShortCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litShortCode As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlSetAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSetAccount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSetAccountOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSetAccountOK As Global.System.Web.UI.WebControls.Button
End Class
