'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POInfo
    
    '''<summary>
    '''pOrderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pOrderInfo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''phStoreManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStoreManager As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''chkStoreManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStoreManager As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''phVendorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phVendorName As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''litVendorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litVendorName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''phVendorList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phVendorList As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''ddlVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVendor As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbtnEditVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnEditVendor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnAddVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnAddVendor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddlAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccount As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbtnAddAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnAddAccount As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddlApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlApprover As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbtnAddApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnAddApprover As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtNeededDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNeededDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlShippingMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlShippingMethod As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''odsShippingMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsShippingMethod As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''txtNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkOversized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOversized As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''chkAttention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAttention As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''btnSavePOInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePOInfo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Alert1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Alert1 As Global.IOF.Web.BootstrapAlert
    
    '''<summary>
    '''VendorInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VendorInfo1 As Global.IOF.Web.Controls.VendorInfo
    
    '''<summary>
    '''pApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pApprover As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlApprovers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlApprovers As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''odsClients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsClients As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''btnAddApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddApprover As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnApproverCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApproverCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblErrApprover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrApprover As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pAccount As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccounts As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''odsAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAccounts As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''btnAddAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAccount As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAccountCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAccountCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblErrAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrAccount As Global.System.Web.UI.WebControls.Label
End Class
