'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POItems
    
    '''<summary>
    '''lblItemDetailsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItemDetailsTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''phItemsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phItemsList As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''ddlItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlItems As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''hidPartNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPartNum As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtPartNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hidDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDescription As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlCat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCat1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''hidCat2ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCat2ID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''txtQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtUnitPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''phInventoryItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phInventoryItem As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''ddlInventoryItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInventoryItem As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkAutoOverwrite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAutoOverwrite As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''btnAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddItem As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateItem As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''phErrItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phErrItem As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''litErrItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litErrItem As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''PurchaseOrderDetailView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PurchaseOrderDetailView1 As Global.IOF.Web.Controls.PurchaseOrderDetailView
    
    '''<summary>
    '''hidSelectedPODID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSelectedPODID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSavePOItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePOItems As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelPOItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelPOItems As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblErrItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrItems As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnOverwriteDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOverwriteDB As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbtnDuplicateInDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnDuplicateInDB As Global.System.Web.UI.WebControls.LinkButton
End Class
