'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Vendors
    
    '''<summary>
    '''phVendorList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phVendorList As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''phStoreManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStoreManager As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''chkStoreManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStoreManager As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''rptVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptVendors As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lbtnAddVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnAddVendor As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''VendorInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VendorInfo1 As Global.IOF.Web.Controls.VendorInfo
End Class
